config/routes.rb
GraphReviewerLy::Application.routes.draw do
  devise_for :users
  resources :users
  resources :graphs
  resources :display_graphs
  
  match "display_graphs/:id/edit_display", :to => "display_graphs#edit_display", :as => "edit_display_graph_display"
  match "display_graphs/:id/update_display", :to => "display_graphs#update_display", :as => "update_display_graph_display", :method => :post
  match "interact/:id", :to => "display_graphs#interact", :as => "interact_display_graph"

  match "t/:token" => "display_graph_tokens#process_token", :as => "process_access_token"
  match "access_token/:display_graph_id/show", :to => "display_graph_tokens#generate_show_token", :as => "generate_show_access_token"
  match "access_token/:display_graph_id/edit", :to => "display_graph_tokens#generate_edit_token", :as => "generate_edit_access_token"

  root :to => "pages#index"

end

app/models/display_graph.rb
class DisplayGraph < ActiveRecord::Base
  belongs_to :graph
  belongs_to :user

  has_many :display_nodes
  has_many :nodes, :through => :display_nodes
  #accepts_nested_attributes_for :display_nodes, :allow_destroy => true
  
  has_many :display_connections
  has_many :connections, :through => :display_connections
  #accepts_nested_attributes_for :display_connections, :allow_destroy => true

  has_many :display_graph_permissions

  after_create :create_default_permission
  after_create :add_all_the_things!


  validates_presence_of :graph_id, :name
  validates_inclusion_of :public, :in => [true, false]

  # not sure if this is necessary
  def create_default_permission
    # that is a fun looking method name
    DisplayGraphPermission.find_or_create_by_display_graph_id_and_user_id(
      :display_graph_id => self.id,
      :user_id => self.user.id,
      :permission_level => "full"
    )
  end

  # automatically adds all the nodes to the display graph
  def add_all_the_things!
    self.graph.nodes.each do |node|
      self.display_nodes.push DisplayNode.new(:node => node, :display_graph => self)
    end

    self.graph.connections.each do |connection|
      self.display_connections.push DisplayConnection.new(:connection => connection, :display_graph => self)
    end
  end

  scope :public_display_graphs, lambda { where(:public => true) }

  # get the display graphs the user has permissions for
  # and the public ones
  # this seems sort of messy
  # this could potentially return the same display graph multiple times
  def self.by_permissions(user)
    DisplayGraphPermission.where(:user_id => user.id).collect { |p| p.display_graph } | DisplayGraph.public_display_graphs
  end

  # determines if the user has display graph permissions of the given level
  # this needs to be seriously refactored
  def has_permission?(user, perm_level)
    perm = display_graph_permissions.where(:user_id => user.id).first
    if perm.nil?
      return false
    elsif perm_level == "show"
      if self.public? || perm.permission_level == "show" || perm.permission_level == "edit" || perm.permission_level == "full" 
        return true
      end
    elsif perm_level == "edit"
      if perm.permission_level == "edit" || perm.permission_level == "full" 
        return true
      end
    elsif perm_level == "full"
      if perm.permission_level == "full" 
        return true
      end
    end
    return false
  end

  # converts the display graph to json so it can be passed through an ajax callback
  def to_json
    output = {}
    output[:name] = self.name
    output[:id] = self.id

    output[:nodes] = []
    self.display_nodes.each do |node|
      output[:nodes].push(node.to_json)
    end

    output[:connections] = []
    self.display_connections.each do |connection|
      output[:connections].push(connection.to_json)
    end
    return output 
  end

  # only updating information on the nodes for now
  def update_positions(data)
    # json doesn't seem to include empty arrays
    if data[:nodes]
      data[:nodes].each do |data_node|
        self.display_nodes.find(data_node[:id]).update_position(data_node)
      end
    end
    return true
  end
end

app/controllers/display_graphs_controller.rb
class DisplayGraphsController < ApplicationController
  load_and_authorize_resource

  before_filter :check_show_permission, :only => [ :show, :interact ]
  before_filter :check_edit_permission, :only => [ :edit, :display ]
  before_filter :check_full_permission, :only => [ :destroy ]

  def check_show_permission
    @display_graph = DisplayGraph.find(params[:id])
    if !@display_graph.has_permission?(current_user, "show")
      redirect_to display_graphs_path, :notice => "You do not have enough permissions to view this page"
    end
  end

  def check_edit_permission
    @display_graph = DisplayGraph.find(params[:id])
    if !@display_graph.has_permission?(current_user, "edit")
      redirect_to display_graphs_path, :notice => "You do not have enough permissions to view this page"
    end
  end

  def check_edit_permission
    @display_graph = DisplayGraph.find(params[:id])
    if !@display_graph.has_permission?(current_user, "full")
      redirect_to display_graphs_path, :notice => "You do not have enough permissions to view this page"
    end
  end

  def index
    if current_user.has_role?(:admin)
      @display_graphs = DisplayGraph.all
    else
      @display_graphs = DisplayGraph.by_permissions(current_user)
    end

    respond_to do |format|
      format.html
    end
  end

  def show
    @display_graph = DisplayGraph.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def new
    @display_graph = DisplayGraph.new

    respond_to do |format|
      format.html
    end
  end

  def edit 
    @display_graph = DisplayGraph.find(params[:id])

    respond_to do |format|
      format.html
    end
  end
  
  def create
    @display_graph = DisplayGraph.new(params[:display_graph])
    @display_graph.user = current_user

    respond_to do |format|
      if @display_graph.save
        format.html { redirect_to(@display_graph, :notice => "Created a display graph") }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @display_graph = DisplayGraph.find(params[:id])

    respond_to do |format|
      if @display_graph.update_attributes(params[:display_graph])
        format.html { redirect_to(@display_graph, :notice => "Updated a display graph") }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @display_graph = DisplayGraph.find(params[:id])
    @display_graph.destroy

    respond_to do |format|
      format.html { redirect_to(display_graphs_url) }
    end
  end

  def edit_display
    @display_graph = DisplayGraph.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def update_display
    @display_graph = DisplayGraph.find(params[:id])

    respond_to do |format|
      if @display_graph.update_attributes(params[:display_graph])
        format.html { redirect_to(@display_graph, :notice => "Updated a display") }
      else
        format.html { render :action => "edit_display" }
      end
    end
  end

  def interact
    @display_graph = DisplayGraph.find(params[:id])

    respond_to do |format|
      format.html { render :layout => "full_screen" }
    end
  end
end

app/views/display_graphs/_display_connection_fields.html.haml
.fields
  = f.input :connection, :as => :select, :collection => Connection.where(:graph_id => @display_graph.graph.id)
  = f.hidden_field :_destroy
  = link_to_function "remove", "remove_fields(this)"

app/views/display_graphs/_display_node_fields.html.haml
.fields
  = f.input :node, :as => :select, :collection => Node.where(:graph_id => @display_graph.graph.id)
  = f.hidden_field :_destroy
  = link_to_function "remove", "remove_fields(this)"

app/views/display_graphs/_form.html.haml
= semantic_form_for @display_graph do |f|
  = f.semantic_errors
  = f.inputs do
    = f.input :graph, :as => :select, :collection => Graph.by_user(current_user)
    = f.input :name
    = f.input :public
  = f.buttons

app/views/display_graphs/edit.html.haml
Edit a display graph

= render :partial => "form"

= link_to 'Show', @display_graph
\|
= link_to 'Back', display_graphs_path

app/views/display_graphs/edit_display.html.haml
Editing the display for #{@display_graph.name}

= semantic_form_for @display_graph, :url => update_display_graph_display_path(@display_graph), :method => :post do |f|
  = f.semantic_errors
  = f.inputs do
    = f.input :nodes, :as => :check_boxes, :collection => @display_graph.graph.nodes.ordered_by_name
    = f.input :connections, :as => :check_boxes, :collection => @display_graph.graph.connections.sort_by(&:name)
  = f.buttons

= link_to 'Show', @display_graph
\|
= link_to 'Back', display_graphs_path

app/views/display_graphs/index.html.haml
%h1 Listing Display Graphs 

%table
  %tr
    %th Name
    %th User
    %th Graph 
    %th
    %th
    %th
    %th
    %th
  - @display_graphs.each do |display_graph|
    %tr
      %td= display_graph.name
      %td= display_graph.user.name
      %td= display_graph.graph.name
      - if display_graph.has_permission?(current_user, "show")
        %td= link_to "Show", display_graph_path(display_graph)
        %td= link_to "Interact", interact_display_graph_path(display_graph)
      - if display_graph.has_permission?(current_user, "edit")
        %td= link_to "Edit", edit_display_graph_path(display_graph)
        %td= link_to "Edit Display", edit_display_graph_display_path(display_graph)
      - if display_graph.has_permission?(current_user, "full")
        %td= link_to 'Destroy', display_graph, :confirm => 'Are you sure?', :method => :delete

= link_to "New Display Graph", new_display_graph_path

app/views/display_graphs/interact.html.haml
-# this probably goes into assets somewhere
<script src="http://graphs.jeremiahhemphill.com:8080/socket.io/socket.io.js"></script>

-# sets the graph structure variable so that is available to paper
:javascript
  var initial_graph_structure = #{@display_graph.to_json.to_json};
  var graph_structure_changes = {}
  var socket_id = 0
  var display_graph_id = #{@display_graph.id}

  var socket = io.connect('http://graphs.jeremiahhemphill.com:8080', { display_graph_id: display_graph_id })
  socket.on('init_data', function(data)  {
    socket_id = data.my_id
    socket.emit('register_user', { display_graph_id: display_graph_id });
  });

  function send_changes_to_server(structure_changes)  {
    var output = { display_graph_id: display_graph_id, changes: structure_changes }
    socket.emit('structure_changes', output)
  }

  socket.on('structure_changes', function(data)  {
    graph_structure_changes = data.changes
  });

= render :partial => "/tokens/generate_token"

<canvas id="display_graph_canvas" resize="true" keepalive="true">
</canvas>

:plain
  <script type='text/paperscript' canvas='display_graph_canvas'>
    var hit_options = {
      fill: true,
      tolerance: 5,
    }

    var Graph = Base.extend({
      name: "",
      id: 0,
      nodes: {},
      connections: {},
      selected_node: null,
      initialize: function(graph_structure)  {
        this.name = graph_structure.name
        this.id = graph_structure.id

        for(var i = 0; i < graph_structure.nodes.length; i++)  {
          node_attributes = graph_structure.nodes[i]
          this.nodes[node_attributes.id] = new Node(this, node_attributes)
        }
        for(var i = 0; i < graph_structure.connections.length; i++)  {
          connection_attributes = graph_structure.connections[i]
          this.connections[connection_attributes.id] = new Connection(this, connection_attributes)
        }
      },
      find_node_by_id: function(id)  {
        return this.nodes[id]
      },
      handle_mouse_down: function(event)  {
        var hit_result = project.hitTest(event.point, hit_options);
        this.selected_path = null;
        if(hit_result && hit_result.type == 'fill')  {
          for(var key in this.nodes)  {
            if(this.nodes[key].rounded_rect == hit_result.item)  {
              this.selected_path = this.nodes[key] 
            }
          }
        }
      },
      handle_mouse_move: function(event)  {
        var hit_result = project.hitTest(event.point, hit_options);
        project.activeLayer.selected = false;
        if (hit_result && hit_result.item)  {
          hit_result.item.selected = true;
        }
      },
      handle_mouse_drag: function(event)  {
        if(this.selected_path)  {
          this.selected_path.update_position(event.delta)
        }
      },
      redraw: function()  {
        for(var key in this.nodes)  {
          this.nodes[key].redraw()
        }
        for(var key in this.connections)  {
          this.connections[key].redraw()
        }
      },
      get_changes: function()  {
        var changes = {}
        for(var key in this.nodes)  {
          if(this.nodes[key].changed)  {
            changes[key] = this.nodes[key].get_changes()
          }
        }
        return changes
      },
    });

    var Node = Base.extend({
      graph: null,
      id: 0,
      position: null,
      bounding_box: null,
      rounded_rect: null,
      text: null,
      scale: 0,
      name: "",
      changed: false,
      fields: {},
      initialize: function(graph, attributes)  {
        this.graph = graph

        this.id = attributes.id
        this.scale = attributes.scale
        this.name = attributes.name
        for(var field_attributes in attributes.fields)  {
          this.fields[field_attributes.id] = new Field(this.graph, field_attributes)
        }

        this.position = new Point(attributes.x_pos, attributes.y_pos)
        var rectangle_size = new Size(200, 40)
        this.bounding_box = new Rectangle(this.position, rectangle_size)
        var corner_size = new Size(10, 10)
        this.rounded_rect = new Path.RoundRectangle(this.bounding_box, corner_size)
        this.rounded_rect.style = {
          fillColor: "black",
          strokeColor: "green",
        }

        this.text = new PointText(this.center)
        this.text.paragraphStyle.justification = 'center'
        this.text.characterStyle.fontSize = 10 * this.scale
        this.text.fillColor = 'green'
        this.text.content = this.name

        //sets the location of the parts
        //there is a bug somewhere in the above code that puts the text and rect in the wrong place
        this.update_parts()
      },
      center: function()  {
        return this.position
      },
      update_position: function(delta)  {
        this.position += delta
        this.update_parts()
        this.changed = true
      },
      update_parts: function()  {
        this.bounding_box.point = this.position
        this.rounded_rect.position = this.bounding_box.point
        this.text.position = this.position
      },
      //when you get the changes, set changed to false
      get_changes: function()  {
        if(this.changed)  {
          this.changed = false
          var changes = {
            x_pos: this.position.x,
            y_pos: this.position.y,
            scale: this.scale,
          }
          return changes
        }
      },
      //if not changed, and there are updated in the changes object
      //the change the position and scale to the given position and scale
      redraw: function()  {
        if(!this.changed && graph_structure_changes.hasOwnProperty(this.id))  {
          changed_node = graph_structure_changes[this.id]
          if(changed_node)  {
            this.position.x = changed_node.x_pos
            this.position.y = changed_node.y_pos
            this.scale = changed_node.scale
            this.update_parts()
          }
        }
      },
    });

    var Field = Base.extend({
      graph: null,
      id: 0,
      name: "",
      initializer: function(graph, attributes)  {
        this.graph = graph

        this.id = attributes.id
        this.name = attributes.name
      },
    });

    var Connection = Base.extend({
      graph: null,
      id: 0,
      //instead of storing ids, we could just store a full link to the node
      //possibly save some processing time
      start_node_id: 0,
      end_node_id: 0,
      start_type: "",
      end_type: "",
      line_type: "",
      weight: "",
      path: null,
      initialize: function(graph, attributes)  {
        this.graph = graph

        this.id = attributes.id
        this.start_node_id = attributes.start_node_id
        this.end_node_id = attributes.end_node_id
        this.start_type = attributes.start_type
        this.end_type = attributes.end_type
        this.line_type = attributes.line_type
        this.weight = attributes.weight

        this.create_or_update_path()
      },
      //checks if both nodes exist, then sets the connection to their location
      create_or_update_path: function()  {
        //if it exists, assume everything is fine
        if(this.path)  {
          this.path.segments[0].point = this.graph.find_node_by_id(this.start_node_id).center()
          this.path.segments[1].point = this.graph.find_node_by_id(this.end_node_id).center()
        } else {
          var start_node = this.graph.find_node_by_id(this.start_node_id)
          var end_node = this.graph.find_node_by_id(this.end_node_id)
          if(start_node && end_node)  {
            this.path = new Path()
            this.path.add(start_node.center())
            this.path.add(end_node.center())
            this.path.style = {
              strokeColor: "green",
              strokeWidth: 1, //no support for weight yet
              //no support for line type yet
            }
          }
        }
      },
      redraw: function()  {
        this.create_or_update_path()
      },
    });

    //setup the canvas
    var background = new Path.Rectangle(view.bounds);
    background.fillColor = 'black';

    graph = new Graph(initial_graph_structure);

    function onFrame(event)  {
      graph.redraw();
      graph_structure_changes = graph.get_changes()

      // get the size of the changes
      // seems sort of silly
      var count = 0;
      for (var p in graph_structure_changes) {
        if (graph_structure_changes.hasOwnProperty(p)) {
          count++;
        }
      }
      if(count > 0)  {
        send_changes_to_server(graph_structure_changes)
      }
    }

    function onMouseDown(event)  {
      graph.handle_mouse_down(event)
    }

    function onMouseMove(event)  {
      graph.handle_mouse_move(event)
    }

    function onMouseDrag(event)  {
      graph.handle_mouse_drag(event)
    }
  </script>

app/views/display_graphs/new.html.haml
Create a display graph

= render :partial => "form"

= link_to 'Back', display_graphs_path

app/views/display_graphs/paper_test.html.erb
<script type='text/javascript'>
//to be available to paperscript, things need to be outside the document ready
var audits = {};
$(document).ready(function()  {
  var last_update_timestamp = 0;

  function get_audits()  {
    return audits;
  }

  //update the canvas with an ajax call to the controller
  function update_audits()  {
    timestamp = self.last_update_timestamp
    $.ajax({
      url: "/acts_as_audited_visualizer/update_audits/" + timestamp,
      dataType: "json",
      success: function(json)  {
        self.last_update_timestamp = Number(new Date());
        //add the new data to the content div
        audits = $.extend(audits, json);
      }
    });
  }

  //update the canvas every few seconds
  function start_updating() {
    setInterval(update_audits, 10000);
  }  

  //get initial canvas
  update_audits();
  setTimeout(start_updating, 2000);
});
</script>
<script type="text/paperscript" canvas="visualization_canvas">
  //create a background the size of the canvas
  var background = new Path.Rectangle(view.bounds);
  background.fillColor = 'black';

  //list of audit objects that have been converted for paperscript
  var audit_list = {};
  //list of model objects that have veen converted for paperscript
  var model_list = new Array();
  //hash of colors for models
  var model_colors = {};
  var model_colors_size = 0;
  var available_colors = ["green", "blue", "red", "teal", "orange", "purple"];

  function find_or_create_model(new_model)  {
    for(var i = 0; i < model_list.length; i++)  {
      if(model_list[i].is_self(new_model))  {
        return model_list[i]
      }
    }
    //optional code to set the color of the models
    //feels like it needs a rewrite
    model_type = new_model.model
    if(!(model_type in model_colors))  {
      model_colors[model_type] = available_colors[(model_colors_size % available_colors.length)];
      model_colors_size++;
    }
    //finish setting code color
    model = new Model(new_model, Point.random() * view.size, 1, 0.5, model_colors[model_type]);
    model_list.push(model);
    return model;
  }

  function onFrame(event) {
    for(var key in audits)  {
      if(! (key in audit_list) )  {
        new_audit = new Audit(key)
        for(var i = 0; i < audits[key].length; i++)  {
          new_model = audits[key][i];
          model = find_or_create_model(new_model);
          new_audit.add_model(model);
        }
        audit_list[new_audit.audit_id] = new_audit;
      }
    }
    for(var i = 0; i < model_list.length; i++)  {
      model_list[i].run(model_list);
    }
  }

  function onMouseDown(event)  {
  }

  //stores an audit and all of its associated models
  var Audit = Base.extend({
    audit_id: 0,
    initialize: function(audit_id)  {
      this.audit_id = audit_id;
      this.models = new Array;
    },
    add_model: function(model)  {
      for(var i = 0; i < this.models.length; i++)  {
        connection = new Connection(this.models[i], model);
      }
      this.models.push(model);
    }
  });

  var Connection = Base.extend({
    initialize: function(start, end)  {
      this.connection = new Path();
      this.connection.strokeColor = "white";
      this.start = start;
      this.end = end;

      start_point = start.add_connection(this);
      end_point = end.add_connection(this);

      this.connection.add(start_point);
      this.connection.add(end_point);
    },
    update: function(caller, new_pos)  {
      if(caller == this.start)  {
        this.connection.segments[0].point.x = new_pos.x;
        this.connection.segments[0].point.y = new_pos.y;
      } else  {
        this.connection.segments[1].point.x = new_pos.x;
        this.connection.segments[1].point.y = new_pos.y;
      }
    },
    get_other_model: function(model)  {
      if(model == this.start)  {
        return this.end
      } else {
        return this.start
      }
    },
  });

  //stores a model that isn't an audit and links it to the audits
  var Model = Base.extend({
    model_id: 0,
    model_type: "",
    initialize: function(model_obj, position, max_speed, max_force, color)  {
      this.model_id = model_obj.id;
      this.model_type = model_obj.model;
      
      var strength = Math.random() * 0.5;
      this.acceleration = new Point(0, 0);
      this.velocity = new Point(Math.random() * 2 - 1, Math.random() * 2 - 1);
      this.loc = position.clone();
      this.radius = 30;
      this.max_speed = max_speed + strength;
      this.max_force = max_force + strength;

      this.shape = new Path.Circle(this.loc, this.radius);
      this.shape.strokeColor = "white";
      this.shape.fillColor = color;

      this.title_text = new PointText(this.loc);
      this.title_text.paragraphStyle.justification = 'center';
      this.title_text.characterStyle.fontSize = 10;
      this.title_text.fillColor = 'white';
      this.title_text.content = this.model_type + ": " + this.model_id;

      this.connections = new Array;
    },
    is_self: function(model)  {
      return (model.model == this.model_type && model.id == this.model_id);
    },
    add_connection: function(path)  {
      this.connections.push(path);
      return this.shape.position;
    },
    run: function(model_list)  {
      this.prev_loc = this.loc.clone();
      this.flock(model_list)

      this.borders();
      this.update();
      
      this.shape.position = this.loc;
      this.title_text.position = this.loc;
      for(var i = 0; i < this.connections.length; i++)  {
        this.connections[i].update(this, this.shape.position);
      }
    },
    //update the position based on the borders of the view
    borders: function() {
      var loc = this.loc;
      var radius = this.radius;
      var old_loc = this.loc.clone();
      var width = view.size.width;
      var height = view.size.height;
      if (loc.x < -radius) loc.x = width + radius;
      if (loc.y < -radius) loc.y = height + radius;
      if (loc.x > width + radius) loc.x = -radius;
      if (loc.y > height + radius) loc.y = -radius;
      var vector = this.loc - old_loc;
      //not sure what this does
      //if (!vector.isZero())  {
      //  this.path.position += vector;
      //}
    },
    flock: function(all_models)  {
      var connected_models = new Array;
      for(var i = 0; i < this.connections.length; i++)  {
        connected_models.push(this.connections[i].get_other_model());
      }
      //maintain distance between all models
      var sep = this.separate(all_models) * 3;
      //match speed with connected models
      var ali = this.align(connected_models);
      //move towards the center of all connected models
      var coh = this.cohesion(connected_models);
      this.acceleration += sep + ali + coh;
    },
    separate: function(all_models)  {
      var desired_separation = 60;
      var steer = new Point(0, 0);
      var count = 0;
      // For every modelin the system, check if it's too close
      for (var i = 0; i < all_models.length; i++) {
        var other = all_models[i];
        var distance = other.loc.getDistance(this.loc);
        //ignore self because distance will be 0
        if (distance > 0 && distance < desired_separation) {
          // Calculate vector pointing away from neighbor
          var diff = this.loc - other.loc;
          steer += diff.normalize(1 / distance);
          count++;
        }
      }
      // Average -- divide by how many
      if (count > 0)  {
        steer /= count;
      }
      if (steer.length > 0) {
        // Implement Reynolds: Steering = Desired - Velocity
        steer.length = this.max_speed;
        steer -= this.velocity;
        steer.length = Math.min(steer.length, this.max_force);
      }
      return steer;
    },
    align: function(connected_models) {
      var steer = new Point(0, 0);
      var count = 0;
      for (var i = 0; i < connected_models.length; i++) {
        var other = connected_models[i];
        var distance = this.loc.getDistance(other.loc);
        if (distance > 0) {
          steer += other.velocity;
          count++;
        }
      }

      if (count > 0)  {
        steer /= count;
      }
      if (steer.length > 0) {
        // Implement Reynolds: Steering = Desired - Velocity
        steer.length = this.max_speed;
        steer -= this.velocity;
        steer.length = Math.min(steer.length, this.max_force);
      }
      return steer;
    },
    cohesion: function(connected_models) {
      var neighborDist = 100;
      var sum = new Point(0, 0);
      var count = 0;
      for (var i = 0; i < connected_models.length; i++) {
        var other = connected_models[i];
        var distance = this.loc.getDistance(other.loc);
        if (distance > 0) {
          sum += other.loc; // Add location
          count++;
        }
      }
      if (count > 0) {
        sum /= count;
        // Steer towards the location
        return this.steer(sum, false);
      }
      return sum;
    },
    steer: function(target, slowdown) {
      var steer,
      desired = target - this.loc,
      distance = desired.length;
      if (distance > 0) {
        // Two options for desired vector magnitude (1 -- based on distance, 2 -- maxSpeed)
        if (slowdown && distance < 100) {
          desired.length = this.max_speed * (distance / 100); // This damping is somewhat arbitrary
        } else {
          desired.length = this.max_speed;
        }
        steer = desired - this.vel;
        steer.length = Math.min(this.max_force, steer.length);
      } else {
        steer = new Point(0, 0);
      }
      return steer;
    },
    update: function() {
      // Update velocity
      this.velocity += this.acceleration;
      // Limit speed (vector#limit?)
      this.velocity.length = Math.min(this.max_speed, this.velocity.length);
      this.loc += this.velocity;
      // Reset acceleration to 0 each cycle
      this.acceleration.length = 0;
    },
  });
</script>
<canvas id="visualization_canvas" resize>
</canvas>

app/views/display_graphs/show.html.haml
%p
  %b Name
  = @display_graph.name
%p
  %b Graph
  = @display_graph.graph.name
%p
  %b Public
  = @display_graph.public
%p
  %b Users
  %table
    %tr
      %th Name
      %th Permission level
    - @display_graph.display_graph_permissions.each do |perm|
      %tr
        %td= perm.user.name
        %td= perm.permission_level
  %hr

- if @display_graph.display_nodes.count > 0
  %p
    %h4 Nodes
    %ul
      - @display_graph.display_nodes.each do |node|
        %li= node.name
    %hr
- if @display_graph.display_connections.count > 0
  %p
    %h4 Connections
    %ul
      - @display_graph.display_connections.each do |connection|
        %li= connection.name
    %hr

= link_to 'Edit', edit_display_graph_path(@display_graph)
\|
= link_to 'Back', display_graphs_path