config/routes.rb
GraphReviewerLy::Application.routes.draw do
  devise_for :users
  resources :users
  resources :graphs
  resources :display_graphs
  
  match "display_graphs/:id/edit_display", :to => "display_graphs#edit_display", :as => "edit_display_graph_display"
  match "display_graphs/:id/update_display", :to => "display_graphs#update_display", :as => "update_display_graph_display", :method => :post
  match "interact/:id", :to => "display_graphs#interact", :as => "interact_display_graph"

  match "t/:token" => "display_graph_tokens#process_token", :as => "process_access_token"
  match "access_token/:display_graph_id/show", :to => "display_graph_tokens#generate_show_token", :as => "generate_show_access_token"
  match "access_token/:display_graph_id/edit", :to => "display_graph_tokens#generate_edit_token", :as => "generate_edit_access_token"

  root :to => "pages#index"

end

app/models/graph.rb
class Graph < ActiveRecord::Base
  belongs_to :user
  has_many :nodes
  has_many :connections

  has_many :display_graphs

  after_save :process_raw_input

  validates_presence_of :name, :raw_input, :user_id

  def process_raw_input
    parsed_graph = Cabbage.dotfile(self.raw_input)

    parsed_graph.nodes.each do |node_hash|
      node = Node.where(:graph_id => self.id, :name => node_hash[:name]).first
      if node.nil?
        node = Node.create(:graph_id => self.id, :name => node_hash[:name])
        puts "creating node #{node.inspect}"
      end

      node_hash[:fields].each do |field|
        if Field.where(:node_id => node.id, :name => node_hash[:name]).count == 0
          field = Field.create(:node_id => node.id, :name => field[:name] )
          puts "creating field #{field.inspect}"
        end
      end
    end

    parsed_graph.connections.each do |connection|
      puts connection.inspect
      start_node = Node.where(:graph_id => self.id, :name => connection[:start_node]).first
      end_node = Node.where(:graph_id => self.id, :name => connection[:end_node]).first

      # naively assumes there is only one connection between each node
      # doing this because I am lazy and it makes the coding easier
      existing_connection = Connection.where(:graph_id => self.id, :start_node_id => start_node.id, :end_node_id => end_node.id).first
      if existing_connection.nil?
        new_connection = Connection.create(
          :graph_id => self.id, 
          :start_node_id => start_node.id,
          :end_node_id => end_node.id,
          :start_type => connection[:arrowhead],
          :end_type => connection[:arrowtail],
          :weight => connection[:weight],
          :line_type => "" # no support yet
        )
        puts "creating connection #{connection.inspect}"
      end
    end
  end

  scope :by_user, lambda { |user| where(:user_id => user.id) }

  def in_use?
    self.display_graphs.count > 0
  end
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  load_and_authorize_resource

  def index
    if current_user.has_role?(:admin)
      @graphs = Graph.all
    else
      @graphs = Graph.by_user(current_user)
    end

    respond_to do |format|
      format.html
    end
  end

  def show
    @graph = Graph.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def new
    @graph = Graph.new

    respond_to do |format|
      format.html
    end
  end

  def edit 
    @graph = Graph.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def create
    @graph = Graph.new(params[:graph])
    @graph.user = current_user

    respond_to do |format|
      if @graph.save
        format.html { redirect_to(@graph, :notice => "Created a graph") }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @graph = Graph.find(params[:id])

    respond_to do |format|
      if @graph.update_attributes(params[:graph])
        format.html { redirect_to(@graph, :notice => "Updated a graph") }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @graph = Graph.find(params[:id])
    @graph.destroy

    respond_to do |format|
      format.html { redirect_to(graphs_url) }
    end
  end
end

app/views/graphs/_form.html.haml
User should not be ediatble, it should be set in the controller
= semantic_form_for @graph do |f|
  = f.semantic_errors
  = f.inputs do
    = f.input :name, :input_html => { :size => 75 }
    = f.input :raw_input, :as => :text, :input_html => { :rows => 10, :cols => 75 }
  = f.buttons

app/views/graphs/edit.html.haml
Editing a Graph

= render :partial => "form"

= link_to 'Show', @graph
\|
= link_to 'Back', graphs_path

app/views/graphs/index.html.haml
%h1 Listing Graphs

%table
  %tr
    %th Name
    %th User
    %th
    %th
    %th
  - @graphs.each do |graph|
    %tr
      %td= graph.name
      %td= graph.user.name
      %td= link_to "Show", graph_path(graph)
      %td= link_to "Edit", edit_graph_path(graph)
      %td
        - unless graph.in_use?
          = link_to 'Destroy', graph, :confirm => 'Are you sure?', :method => :delete

= link_to "New Graph", new_graph_path

app/views/graphs/new.html.haml
Creating a Graph

= render :partial => "form"

= link_to 'Back', graphs_path

app/views/graphs/show.html.haml
%p
  %b Name:
  = @graph.name
%p
  %b User:
  = @graph.user.name
- if @graph.nodes.count > 0
  %p
    %h4 Nodes
    %ul
      - @graph.nodes.ordered_by_name.each do |node|
        %li= node.name
    %hr
- if @graph.connections.count > 0
  %p
    %h4 Connections
    %ul
      - @graph.connections.sort_by(&:name).each do |connection|
        %li= connection.name
    %hr

= link_to 'Edit', edit_graph_path(@project)
\|
= link_to 'Back', graphs_path