config/routes.rb
GraphReviewerLy::Application.routes.draw do
  devise_for :users
  resources :users
  resources :graphs
  resources :display_graphs
  
  match "display_graphs/:id/edit_display", :to => "display_graphs#edit_display", :as => "edit_display_graph_display"
  match "display_graphs/:id/update_display", :to => "display_graphs#update_display", :as => "update_display_graph_display", :method => :post
  match "interact/:id", :to => "display_graphs#interact", :as => "interact_display_graph"

  match "t/:token" => "display_graph_tokens#process_token", :as => "process_access_token"
  match "access_token/:display_graph_id/show", :to => "display_graph_tokens#generate_show_token", :as => "generate_show_access_token"
  match "access_token/:display_graph_id/edit", :to => "display_graph_tokens#generate_edit_token", :as => "generate_edit_access_token"

  root :to => "pages#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :role_assignments
  has_many :roles, :through => :role_assignments
  attr_accessible :role_ids

  after_create :set_default_role

  def set_default_role
    self.roles.push(Role.find_by_name("basic_user"))
  end

  def name
    self.email
  end

  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  # GET /users
  # GET /users.xml
  def index
    @users = User.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(manage_users_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/users/_form.html.haml
= semantic_form_for @user do |f|
  = f.semantic_errors
  = f.inputs do
    = f.input :roles, :as => :check_boxes
  = f.buttons

app/views/users/edit.html.haml
%h2 
  Editing roles for 
  = @user.name

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users 

= paginate @users
%table
  %tr
    %th Name
    %th Roles
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td
        - if user.roles.length > 0
          %ul
            - user.roles.each do |role|
              %li= role.name
          
      %td= link_to 'Show', user_path(user)
      %td= link_to 'Edit Roles', edit_user_path(user)
      %td= button_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

app/views/users/show.html.haml
%p
  %b Name:
  = @user.name
%p
  %b Roles:
  %ul
    - @user.roles.each do |role|
      %li= role.name

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path