config/routes.rb
GraphReviewerLy::Application.routes.draw do
  devise_for :users
  resources :users
  resources :graphs
  resources :display_graphs
  
  match "display_graphs/:id/edit_display", :to => "display_graphs#edit_display", :as => "edit_display_graph_display"
  match "display_graphs/:id/update_display", :to => "display_graphs#update_display", :as => "update_display_graph_display", :method => :post
  match "interact/:id", :to => "display_graphs#interact", :as => "interact_display_graph"

  match "t/:token" => "display_graph_tokens#process_token", :as => "process_access_token"
  match "access_token/:display_graph_id/show", :to => "display_graph_tokens#generate_show_token", :as => "generate_show_access_token"
  match "access_token/:display_graph_id/edit", :to => "display_graph_tokens#generate_edit_token", :as => "generate_edit_access_token"

  root :to => "pages#index"

end

app/views/shared/_navigation.html.haml
- if user_signed_in?
  %ul{"class" => "tabs"}
    %li= link_to "Home", root_path
    - if can? :read, User
      %li= link_to "Manage Users", users_path
    - if can? :read, Graph 
      %li= link_to "Manage Graphs", graphs_path 
    - if can? :read, DisplayGraph 
      %li= link_to "Manage Display Graphs", display_graphs_path 

app/views/shared/_user_login_state.html.haml
.sign_in_status
  - if user_signed_in?
    You are signed in as:
    = current_user.email
    = link_to "Sign Out", destroy_user_session_path, :method => "delete"
  - else
    = link_to "Sign In", new_user_session_path
    = link_to "Sign Up", new_user_registration_path